// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hesapkitap.data.Concrete.EfCore;

namespace hesapkitap.data.Migrations
{
    [DbContext(typeof(HesapKitapContext))]
    partial class HesapKitapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("hesapkitap.entity.DegerKisitla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DegerAdi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DegerKisitlas");
                });

            modelBuilder.Entity("hesapkitap.entity.GiderEkle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AitOlduguDonem")
                        .HasColumnType("TEXT");

                    b.Property<int>("GiderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OdemeKontrol")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdemeTuru")
                        .HasColumnType("TEXT");

                    b.Property<int>("OdemeTuruId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnKasaKontrol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnKasaTutar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tutar")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunAdı")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrunKategorisi")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VadeTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GiderEkles");
                });

            modelBuilder.Entity("hesapkitap.entity.GiderKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderEkleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GiderKategoriler")
                        .HasColumnType("TEXT");

                    b.Property<int>("UrunKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GiderKategoris");
                });

            modelBuilder.Entity("hesapkitap.entity.GunSonuKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GunSonuKategoriName")
                        .HasColumnType("TEXT");

                    b.Property<int>("GunSonuTutarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("GunSonuKategoris");
                });

            modelBuilder.Entity("hesapkitap.entity.GunSonuTutar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<int>("GunSonuKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunsonuTutarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGunSonu")
                        .HasColumnType("TEXT");

                    b.Property<int>("OnKasaKontrol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnKasaTutar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<double>("Tutar")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("result")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GunSonuTutars");
                });

            modelBuilder.Entity("hesapkitap.entity.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuTutarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunsonuId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameGunSonu")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YoneticiYetkisiKontrol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Homes");
                });

            modelBuilder.Entity("hesapkitap.entity.HomeGunSonuKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GunSonuKategoriId");

                    b.HasIndex("HomeId");

                    b.ToTable("HomeGunSonuKategori");
                });

            modelBuilder.Entity("hesapkitap.entity.HomeGunSonuTutar", b =>
                {
                    b.Property<int>("GunSonuId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuTutarId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GunSonuId", "GunSonuTutarId");

                    b.HasIndex("GunSonuTutarId");

                    b.HasIndex("HomeId");

                    b.ToTable("HomeGunSonuTutar");
                });

            modelBuilder.Entity("hesapkitap.entity.TarihKontrol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderEkleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GunSonuTutarId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarihAy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarihGun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TarihString")
                        .HasColumnType("TEXT");

                    b.Property<int>("TarihYıl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferEkleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferKalemiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UrunKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TarihKontrols");
                });

            modelBuilder.Entity("hesapkitap.entity.TransferEkle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferAciklama")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TransferKalemiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransferNereden")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferNereye")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferTarihi")
                        .HasColumnType("TEXT");

                    b.Property<double>("TransferTutari")
                        .HasColumnType("REAL");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransferEkles");
                });

            modelBuilder.Entity("hesapkitap.entity.TransferEkleKalem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adı")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TransferEkleId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TransferKalemiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tutar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TransferEkleId");

                    b.HasIndex("TransferKalemiId");

                    b.ToTable("TransferEkleKalem");
                });

            modelBuilder.Entity("hesapkitap.entity.TransferKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adı")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransferKalemis");
                });

            modelBuilder.Entity("hesapkitap.entity.UrunKategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderEkleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GiderKategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrunKategoriName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UrunKategoris");
                });

            modelBuilder.Entity("hesapkitap.entity.HomeGunSonuKategori", b =>
                {
                    b.HasOne("hesapkitap.entity.GunSonuKategori", "GunSonuKategoris")
                        .WithMany("HomeGunSonuKategori")
                        .HasForeignKey("GunSonuKategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hesapkitap.entity.Home", "Home")
                        .WithMany("HomeGunSonuKategoris")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("hesapkitap.entity.HomeGunSonuTutar", b =>
                {
                    b.HasOne("hesapkitap.entity.GunSonuTutar", "GunSonuTutar")
                        .WithMany("HomeGunSonuTutars")
                        .HasForeignKey("GunSonuTutarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("hesapkitap.entity.Home", "Home")
                        .WithMany("HomeGunSonuTutars")
                        .HasForeignKey("HomeId");
                });

            modelBuilder.Entity("hesapkitap.entity.TransferEkleKalem", b =>
                {
                    b.HasOne("hesapkitap.entity.TransferEkle", "TransferEkle")
                        .WithMany("TransferEkleKalem")
                        .HasForeignKey("TransferEkleId");

                    b.HasOne("hesapkitap.entity.TransferKalemi", "TransferKalemi")
                        .WithMany("TransferEkleKalem")
                        .HasForeignKey("TransferKalemiId");
                });
#pragma warning restore 612, 618
        }
    }
}
